twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        version: '%version%'
    form_themes:
        - 'form/fields.html.twig'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/assets/img': images

when@test:
    twig:
        strict_variables: true
