twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        version: '%version%'
    form_themes:
        - 'form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
